data:
  dataset: amazon3m
  is_lf_data: False
  augment_label_data: False
  use_filter_eval: False
  num_labels: 2812281 
  max_len: 128
  num_workers: 8
  batch_size: 128
  test_batch_size: 128
  tokenized_loading: False

#Architectural Settings
model:
  encoder:
    encoder_model: "bert-base-uncased"
    encoder_tokenizer: "${dataset.model.encoder.encoder_model}"
    encoder_ftr_dim: ${encoder_feature_size:${dataset.model.encoder.encoder_model}}
    pool_mode: 'last_nhidden_conlast' 
    feature_layers: 1
    embed_dropout: 0.15
    use_torch_compile: True
    use_ngame_encoder_weights: False
    ngame_checkpoint: ./NGAME_ENCODERS/${dataset.data.dataset}/state_dict.pt

  penultimate:
    use_penultimate_layer: False
    penultimate_size: 64
    penultimate_activation: relu

  ffi:
    use_ht_split: True #whether to use head tail split. if used by default head is selected as dense layer.
    head_ratio: 0.02
    use_sparse_layer: True #if false then classifier layer would be dense.
    use_shared_group: True
    group_size: 64
    cluster_based_grouping: False
    cluster_file: amazon3m_label_embs_06B8000.npz
    fan_in: 128
    prune_mode: fraction
    rewire_threshold: 0.01
    rewire_fraction: 0.25
    growth_mode: random
    growth_init_mode: zero
    input_features: ${input_size_select:${dataset.model.penultimate.use_penultimate_layer},
                          ${dataset.model.penultimate.penultimate_size},${dataset.model.encoder.feature_layers},${dataset.model.encoder.encoder_ftr_dim}}   #set based on penultimate value in Encoder
    output_features: ${dataset.data.num_labels} #depends on num_labels in data
    rewire_interval: 1500
    use_rewire_scheduling: True
    rewire_end_epoch: 0.66   #depends on epoch

  auxiliary:
    use_meta_branch: False
    group_y_group: 0
    meta_cutoff_epoch: 50   # varies based on fan_in values
    auxloss_scaling: 0.5


  private_feature:
    use_private_feature: False #whether to use separate feature neurons for head and tail
    head_start: 384 # out of 768 the initial index of head layer input
    head_end: 768 # out of 768 the final index of head layer input
    tail_start: 0  # out of 768 the initial index of tail layer input
    tail_end: 384 # out of 768 the final index of tail layer input
    head_dropout: 0.25
    tail_dropout: 0.2

#Training related settings
training:
  seed: 42
  amp:
    enabled: False
    dtype: bfloat16

  optimization:
    loss_fn: bce   # ['bce','squared_hinge']
    encoder_optimizer: adamw
    xmc_optimizer: sgd_sr
    epochs: 101  
    grad_accum_step: 1
    encoder_lr: 5.0e-5
    penultimate_lr: 0.001
    meta_lr: 5.0e-4
    lr: 0.05  # learning rate of final layer
    momentum: 0.9
    wd_encoder: 0.01   # weight decay on encoder
    wd: 1e-4  # weight decay of final layer
    lr_scheduler: CosineScheduleWithWarmup   
    lr_scheduler_xmc: CosineScheduleWithWarmup 
    warmup_steps: 10000
    training_steps: 1  #selected at runtime based on batch size and dataloader

  evaluation:
    train_evaluate: False
    train_evaluate_every: 10
    test_evaluate_every: 1
    A: 0.6  # for propensity calculation
    B: 2.6  # for propensity calculation
    eval_psp: True

  verbose:
    show_iter: False  # print loss during training
    print_iter: 2000  # how often (iteration) to print
    use_wandb: False
    wandb_project_name: DST_XMC_HT # project name
    wandb_runname: none
    logging: True
    log_fname: log_amazon3m
    job_num: 0
    
  use_checkpoint: True  #whether to use automatic checkpoint
  checkpoint_file: amazon3m_G32FFI32HT_1.pt
  best_p1: 0.53  # to store the model above this performance in case of automatic checkpoint
